apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-machineset
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: gpu-machineset
    app.kubernetes.io/part-of: litemaas-infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/anatsheh84/litemaas-deployment.git
    targetRevision: HEAD
    path: base/gpu-machineset
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-machine-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
