apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-feature-discovery
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/instance: node-feature-discovery
    app.kubernetes.io/part-of: litemaas-infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/anatsheh84/litemaas-deployment.git
    targetRevision: HEAD
    path: base/nfd
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-nfd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
