apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-gpu-operator
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/instance: nvidia-gpu-operator
    app.kubernetes.io/part-of: litemaas-infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/anatsheh84/litemaas-deployment.git
    targetRevision: HEAD
    path: base/nvidia-gpu-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: nvidia-gpu-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
