apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: cluster-5wkv7-42286-gpu-worker-us-east-2b
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-5wkv7-42286
  annotations:
    capacity.cluster-autoscaler.kubernetes.io/labels: kubernetes.io/arch=amd64,node-role.kubernetes.io/gpu=true
    machine.openshift.io/GPU: "1"
    machine.openshift.io/memoryMb: "32768"
    machine.openshift.io/vCPU: "8"
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-5wkv7-42286
      machine.openshift.io/cluster-api-machineset: cluster-5wkv7-42286-gpu-worker-us-east-2b
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-5wkv7-42286
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: cluster-5wkv7-42286-gpu-worker-us-east-2b
        node-role.kubernetes.io/gpu: ""
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/gpu: ""
      taints:
        - key: nvidia.com/gpu
          value: "true"
          effect: NoSchedule
      providerSpec:
        value:
          ami:
            id: ami-0c8e6bf7411c9db04  # RHCOS AMI for us-east-2
          apiVersion: machine.openshift.io/v1beta1
          blockDevices:
            - ebs:
                encrypted: true
                iops: 0
                kmsKey:
                  arn: ""
                volumeSize: 120
                volumeType: gp3
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: cluster-5wkv7-42286-worker-profile
          instanceType: g5.2xlarge
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          metadataServiceOptions: {}
          placement:
            availabilityZone: us-east-2b
            region: us-east-2
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - cluster-5wkv7-42286-node
            - filters:
                - name: tag:Name
                  values:
                    - cluster-5wkv7-42286-lb
          subnet:
            filters:
              - name: tag:Name
                values:
                  - cluster-5wkv7-42286-subnet-private-us-east-2b
          tags:
            - name: kubernetes.io/cluster/cluster-5wkv7-42286
              value: owned
          userDataSecret:
            name: worker-user-data
