apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litemaas

# Remote resources from upstream LiteMaaS repository
# Using the correct Git URL format with path
resources:
  - namespace.yaml
  - github.com/anatsheh84/litemaas/deployment/openshift?ref=main

# Local secret templates (must be customized before deployment)
# IMPORTANT: Comment out the secretGenerator and use generated-secrets/ instead
# secretGenerator:
#   - name: postgres-secret
#     files:
#       - postgres-secret.yaml
#   - name: backend-secret
#     files:
#       - backend-secret.yaml
#   - name: litellm-secret
#     files:
#       - litellm-secret.yaml

# Common labels
commonLabels:
  app.kubernetes.io/part-of: litemaas
  app.kubernetes.io/managed-by: kustomize
