apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litemaas

# Base OpenShift deployment resources from the upstream litemaas repo
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/anatsheh84/litemaas/main/deployment/openshift/postgres-statefulset.yaml
  - https://raw.githubusercontent.com/anatsheh84/litemaas/main/deployment/openshift/postgres-service.yaml
  - https://raw.githubusercontent.com/anatsheh84/litemaas/main/deployment/openshift/postgres-init-configmap.yaml
  - https://raw.githubusercontent.com/anatsheh84/litemaas/main/deployment/openshift/litellm-deployment.yaml
  - https://raw.githubusercontent.com/anatsheh84/litemaas/main/deployment/openshift/litellm-service.yaml
  - https://raw.githubusercontent.com/anatsheh84/litemaas/main/deployment/openshift/litellm-route.yaml
  - generated-secrets/postgres-secret.yaml
  - generated-secrets/litellm-secret.yaml
  - generated-secrets/backend-secret.yaml
  
  # TODO: Add backend and frontend when images are ready  
  # - https://raw.githubusercontent.com/anatsheh84/litemaas/main/deployment/openshift/backend-deployment.yaml.template
  # - https://raw.githubusercontent.com/anatsheh84/litemaas/main/deployment/openshift/backend-service.yaml
  # - https://raw.githubusercontent.com/anatsheh84/litemaas/main/deployment/openshift/frontend-deployment.yaml.template
  # - https://raw.githubusercontent.com/anatsheh84/litemaas/main/deployment/openshift/frontend-service.yaml
  # - https://raw.githubusercontent.com/anatsheh84/litemaas/main/deployment/openshift/frontend-route.yaml

# Common labels for all resources
commonLabels:
  app.kubernetes.io/part-of: litemaas
  app.kubernetes.io/managed-by: kustomize
