apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
  namespace: litemaas
  labels:
    app: litellm
type: Opaque
stringData:
  # IMPORTANT: Change these values before deploying!
  
  # Master key for LiteLLM proxy
  master-key: "sk-litellm-CHANGEME"
  
  # Database connection string
  database-url: "postgresql://litemaas_admin:CHANGEME_POSTGRES_PASSWORD@postgres:5432/litemaas_db"
  
  # UI admin password (for https://litellm-litemaas.apps.CLUSTER_DOMAIN/ui)
  ui-username: "admin"
  ui-password: "CHANGEME_LITELLM_UI_PASSWORD"
