apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: litemaas
  labels:
    app: postgres
type: Opaque
stringData:
  # IMPORTANT: Change these values before deploying!
  postgres-password: CHANGEME_POSTGRES_PASSWORD
  postgres-user: litemaas_admin
  postgres-db: litemaas_db
